export const GET_DATA = 'GET_DATA'
export const CHECK_ANSWER = 'CHECK_ANSWER'
export const SHOW_QUESTION = 'SHOW_QUESTION'
export const MAKE_HIGHLIGHT = 'MAKE_HIGHLIGHT'
export const FINISH_QUIZ = 'FINISH_QUIZ'
export const TRY_AGAIN = 'TRY_AGAIN'
